default: &default
  ## Secret values encrypted within secrets.yml.enc by secrets.yml.key
  ## Edit with: EDITOR=vim bin/rails secrets:edit

  ## MySQL tables
  gene: geneinfo
  condition: cgd
  phenotype: hpo
  omim: omim
  ref_gene: refgene
  gene_coordinate: gene_coordinate

  # Project ID of the client object
  project_id: "<%= ENV['GCP_PROJECT_ID'] %>"
  scope: "https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/bigquery,https://www.googleapis.com/auth/genomics.readonly,https://www.googleapis.com/auth/devstorage.read_only"

  # Google BigQuery Tables (DB6)
  # NOTE: The default configuration is set for the production use.
  db6:
    # Project ID of the data source
    project_id: <%= ENV['BIGQUERY_PROJECT_ID'] %>
    dataset_id: <%= ENV['BIGQUERY_DATASET_ID'] %>

    tables:
      portal_variants: <%= ENV['BIGQUERY_DATASET_ID'] %>.portal_use_only_feature_variants
      portal_rare_variants: <%= ENV['BIGQUERY_DATASET_ID'] %>.portal_use_only_rare_feature_variants
      annotations: <%= ENV['BIGQUERY_DATASET_ID'] %>.<%= ENV['BIGQUERY_BASE_ANNOTATION_TABLE'] or 'annotations_ilmn' %>  # Base Annotation Table (Illumina)
      subject_samples: <%= ENV['BIGQUERY_DATASET_ID'] %>.subject_sample
      subjects: <%= ENV['BIGQUERY_DATASET_ID'] %>.subject
      de_novo_variants: <%= ENV['BIGQUERY_DATASET_ID'] %>.variants_de_novo
      sanger_variants: <%= ENV['BIGQUERY_DATASET_ID'] %>.variants_sanger
      subject_measures: <%= ENV['BIGQUERY_DATASET_ID'] %>.measures
      sequenced_samples: <%= ENV['BIGQUERY_DATASET_ID'] %>.sequenced_samples
      dbsnp_coordinates: <%= ENV['BIGQUERY_DATASET_ID'] %>.dbsnp_coordinate
      tests: <%= ENV['BIGQUERY_DATASET_ID'] %>.tests
      parental_genotypes: <%= ENV['BIGQUERY_DATASET_ID'] %>.parental_genotypes
    extended_tables:
      complete_genomics:
        annotations: <%= ENV['BIGQUERY_DATASET_ID'] %>.annotations_cg

  # Default selected visible variant columns
  selected_preferences: &selected
    - sample_id
    - reference_name
    - start
    - end
    - reference_bases
    - alternate_bases
    - letter_genotype # computed
    - zygosity # computed
    - call_dp
    - ad
    - call_gq
    - inheritance
    - de_novo
    - refseq_id
    - gene_symbol
    - effects_with_impacts # computed
    - a1000g_freq_max
    - gnomad_genome_freq_max
    - max_int_freq
    - sex
    - platform
    - clinvar_sig_simple
    - clinvar_sig
  # Default unselected (not visible) variant columns
  unselected_preferences: &unselected
#    - category TODO (#137): bring this back when the computation is corrected
#    - prioritizations TODO (#132): bring this back when the computation is corrected
    - gnomad_exome_freq_max
    - exac_freq_max
    - call_filter
#    - comp_het_rec TODO (#131): bring this back when the computation is corrected
    - entrez_id
    - dbsnp
    - cgd_disease
    - cgd_inheritance
    - omim_phenotype
    - effect_priority
    - typeseq_priority
    - affection
    - familyid
    - sanger_validated
    - sanger_inheritance
    - call_ehq
    - call_hq
    - gnomad_oe_lof_upper
    - gnomad_oe_mis_upper
    - gnomad_pli
    - gnomad_prec
    - min_int_ref
    - freq_max
    - comment
  # All potentially selectable visible variant columns
  selectable_preferences: &selectable
    - *selected
    - *unselected
  variant_attrs:
    - select_scope
    - annotation_id
    - sample_id
    - reference_name
    - start
    - end
    - reference_bases
    - alternate_bases
    - associated_alternate_bases
    - letter_genotype # computed
    - zygosity # computed
    - call_dp
    - ad
    - call_gq
    - inheritance
    - de_novo
    - refseq_id
    - gene_symbol
    - effects_with_impacts # computed
    - a1000g_freq_max
    - gnomad_genome_freq_max
    - max_int_freq
    - sex
    - platform
    - category
    - prioritizations
    - gnomad_exome_freq_max
    - exac_freq_max
    - call_filter
    - comp_het_rec
    - entrez_id
    - dbsnp
    - clinvar_sig
    - cgd_disease
    - cgd_inheritance
    - omim_phenotype
    - aggregated_ehq
    - aggregated_hq
    - effect_priority
    - typeseq_priority
    - affection
    - familyid
    - sanger_validated
    - sanger_inheritance
    - call_hq
    - call_ehq
    - genotype # this is computed by letter_genotype and zygosity
    - results_count
    - effect_impact
    - cg_freq_max
    - freq_max
    - nhlbi_freq_max
    - dnasource
    - fatherid
    - familytype
    - motherid
    - subject_id
    - phenotyped
    - source
    - gnomad_oe_lof_upper
    - gnomad_oe_mis_upper
    - gnomad_pli
    - gnomad_prec
    - min_int_ref
    - comment
    - clinvar_sig_simple
  annotated_variant_attrs:
    - select_scope
    - annotation_id
    - sample_id
    - subject_id
    - gene_symbol
    - entrez_id
    - refseq_id
    - genotype
    - sex
    - fatherid
    - motherid
    - affection
    - familyid
    - familytype
    - freq_max
    - a1000g_freq_max
    - '"N/A" AS nhlbi_freq_max'
    - exac_freq_max
    - cg_freq_max
    - gnomad_exome_freq_max
    - gnomad_genome_freq_max
    - effect_impact
    - '"N/A" AS typeseq_priority'
    - '"N/A" AS effect_priority'
    - dbsnp
    - clinvar_sig
    - cgd_disease
    - cgd_inheritance
    - omim_phenotype
    - ad
    - filter AS call_filter
    - dp AS call_dp
    - gq AS call_gq
    - dnasource
    - platform
    - sanger_validated
    - sanger_inheritance
    - de_novo
    - phenotyped
    - reference_name
    - start
    - end
    - reference_bases
    - alternate_bases
    - associated_alternate_bases
    - inheritance
    - comp_het_rec
    - max_int_freq
    - gnomad_oe_lof_upper
    - gnomad_oe_mis_upper
    - gnomad_pli
    - gnomad_prec
    - min_int_ref
    - clinvar_sig_simple
  annotation_attrs:
    - id
    - reference_name
    - start
    - end
    - reference_bases
    - alternate_bases
    - typeseq
    - typeseq_priority
    - refseq_id
    - aa_flag
    - effect
    - effect_priority
    - gene_symbol
    - entrez_id
    - gene_desc
    - gene_type
    - omim_id
    - omim_phenotype
    - MPO
    - HPO
    - CGD_disease
    - CGD_inheritance
    - ACMG_disease
    - Clinvar_SIG
    - '"N/A" AS Clinvar_SIG_ord'
    - Clinvar_CLNREF
    - '"N/A" AS Clinvar_CLNACC'
    - Clinvar_ReviewStatus
    - cosmic
    - A1000g_all
    - A1000g_eur
    - A1000g_amr
    - A1000g_eas
    - A1000g_afr
    - A1000g_sas
    - ExAC_Freq
    - ExAC_AFR
    - ExAC_AMR
    - ExAC_EAS
    - ExAC_FIN
    - ExAC_NFE
    - ExAC_OTH
    - ExAC_SAS
    - cg
    - cg_filtered
    - cgW597_AllFreq
    - cgW597_CalledFreq
    - cgW597_11s
    - cgW597_Hs
    - cgW597_Ls
    - cg1KG436_AllFreq
    - cg1KG436_CalledFreq
    - cg1KG436_11s
    - cg1KG436_Hs
    - cg1KG436_Ls
    - gnomAD_exome_ALL
    - gnomAD_exome_AFR
    - gnomAD_exome_AMR
    - gnomAD_exome_ASJ
    - gnomAD_exome_EAS
    - gnomAD_exome_FIN
    - gnomAD_exome_NFE
    - gnomAD_exome_OTH
    - gnomAD_exome_SAS
    - gnomAD_genome_ALL
    - gnomAD_genome_AFR
    - gnomAD_genome_AMR
    - gnomAD_genome_ASJ
    - gnomAD_genome_EAS
    - gnomAD_genome_FIN
    - gnomAD_genome_NFE
    - gnomAD_genome_OTH
    - dbsnp
    - dbsnp_common
    - dbsnp_region
    - dbsnp_wind
    - sift_score
    - PROVEAN_score
    - polyphen_score
    - ma_score
    - mt_score
    - CADD_phred
    - phylopMam      # Known as phylopPMam in DB5 (typo), corrected in DB6
    - phylopMam_avg  # Known as phylopPMam_avg in DB5 (typo), corrected in DB6
    - phylopVert100
    - phylopVert100_avg
    - phastCons_placental
    - pfam_annovar
    - per_cds_affected
    - per_transcripts_affected
    - spx_dpsi
    - spx_dpsi_z
    - spx_gene
    - spx_strand
    - spx_transcript
    - spx_exonN
    - spx_spliceDist
    - dbscSNV_ADA_SCORE
    - dbscSNV_RF_SCORE
    - SegDup
    - Repeat
    - effect_impact
    - freq_max
    - A1000g_freq_max
    - ExAC_freq_max
    - cg_freq_max
    - gnomAD_exome_freq_max
    - gnomAD_genome_freq_max
    - gnomad_oe_lof  # new in DB6
    - gnomad_oe_lof_upper  # new in DB6
    - gnomad_oe_mis  # new in DB6
    - gnomad_oe_mis_upper  # new in DB6
    - gnomad_pli  # new in DB6
    - gnomad_prec  # new in DB6
    - Annovar_key  # new in DB6
    - clinvar_sig_simple  # new in DB6
    - distance_spliceJunction
    - comment  # new in DB6
    - max_int_freq # renamed from mssng_freq_max in db5
  subject_attrs:
    - indexid
    - fatherid
    - motherid
    - affection
    - sex
    - familyid
    - familytype
    - dob
  subject_sample_attrs:
    - indexid
    - submittedid
    - dnasource
    - platform
    - nimhid
    - rudcrid
    - comments
    - software_version
  subject_measure_attrs:
    - indexid
    - code
    - testdate
    - measure
    - relevance
    - test
    - question
    - legend
  dbsnp_coordinate_attrs:
    - reference_name
    - start
    - end
    - dbsnp
  sequenced_sample_attrs:
    - call_call_set_name

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
