# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22e959b5ede5496139c713bfe96ccd9edcefbd1eed10e7c4d294f873d5d3679907520776d091ab91ebc4b74a06c7e1345109b132aca5ece51577aa85a045cda5
  google_client_id: <%= ENV['GCP_CLIENT_ID'] || '(not a client ID)' %>
  google_secret: <%= ENV['GCP_CLIENT_SECRET'] || '(not a client secret)' %>
  google_tracking_id: <%= ENV['GA_TRACKING_ID'] %>

test:
  secret_key_base: ccabe0a5604e2300b414e85127b997b9f3c6301c28178861980b11a0f458ce707fd4664348c1ad4b8cceb393bcc045217595f5ccdbc3f5bd389451004c971256
  google_client_id: <%= ENV['GCP_CLIENT_ID'] || '(not a client ID)' %>
  google_secret: <%= ENV['GCP_CLIENT_SECRET'] || '(not a client secret)' %>
  google_tracking_id: <%= ENV['GA_TRACKING_ID'] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  # secret_key_base: Rails.application.secrets[:secret_key_base]
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  domain_name: db5.mss.ng
  gmail_username: <%= ENV['SMTP_USERNAME'] || '(not a username)' %>
  gmail_password: <%= ENV['SMTP_PASSWORD'] || '(not a password)' %>
  google_client_id: <%= ENV['GCP_CLIENT_ID'] || '(not a client ID)' %>
  google_secret: <%= ENV['GCP_CLIENT_SECRET'] || '(not a client secret)' %>
  google_tracking_id: <%= ENV['GA_TRACKING_ID'] %>

cucumber:
  # Same as test
  secret_key_base: ccabe0a5604e2300b414e85127b997b9f3c6301c28178861980b11a0f458ce707fd4664348c1ad4b8cceb393bcc045217595f5ccdbc3f5bd389451004c971256
  google_client_id: <%= ENV['GCP_CLIENT_ID'] || '(not a client ID)' %>
  google_secret: <%= ENV['GCP_CLIENT_SECRET'] || '(not a client secret)' %>
  google_tracking_id: <%= ENV['GA_TRACKING_ID'] %>